# Importing Data Using Pandas - Lab

## Introduction

In this lab, you'll get some practice with loading files with summary or metadata, and if you find that easy, the optional "level up" content covers loading data from a currupted csv file!

## Objectives
You will be able to:
* Import data from csv files and Excel files
* Understand and explain key arguments for imports
* Save information to csv and Excel files
* Access data within a Pandas DataFrame (print() and .head())

#  Loading Files with Summary or Meta Data

Load either of the files Zipcode_Demos.csv or Zipcode_Demos.xlsx. What's going on with this dataset? Clean it up into a useable format and describe the nuances of how the data is currently formatted.

All data files are stored in a folder titled 'Data'.

In [4]:
import pandas as pd
df = pd.read_csv("Data/Zipcode_Demos.csv", skiprows=[, nrows=45, usecols=[1,2,3])
df

                             Unnamed: 1          0  Unnamed: 3
0                     JURISDICTION NAME  10005.800         NaN
1                    COUNT PARTICIPANTS      9.400         NaN
2                          COUNT FEMALE      4.800         NaN
3                        PERCENT FEMALE      0.404         NaN
4                            COUNT MALE      4.600         NaN
5                          PERCENT MALE      0.396         NaN
6                  COUNT GENDER UNKNOWN      0.000         NaN
7                PERCENT GENDER UNKNOWN      0.000         NaN
8                    COUNT GENDER TOTAL      9.400         NaN
9                  PERCENT GENDER TOTAL     80.000         NaN
10               COUNT PACIFIC ISLANDER      0.000         NaN
11             PERCENT PACIFIC ISLANDER      0.000         NaN
12                COUNT HISPANIC LATINO      2.000         NaN
13              PERCENT HISPANIC LATINO      0.105         NaN
14                COUNT AMERICAN INDIAN      0.000         NaN
15              PERCENT AMERICAN INDIAN      0.000         NaN
16             COUNT ASIAN NON HISPANIC      3.600         NaN
17           PERCENT ASIAN NON HISPANIC      0.437         NaN
18             COUNT WHITE NON HISPANIC      0.800         NaN
19           PERCENT WHITE NON HISPANIC      0.036         NaN
20             COUNT BLACK NON HISPANIC      2.600         NaN
21           PERCENT BLACK NON HISPANIC      0.181         NaN
22                COUNT OTHER ETHNICITY      0.400         NaN
23              PERCENT OTHER ETHNICITY      0.040         NaN
24              COUNT ETHNICITY UNKNOWN      0.000         NaN
25            PERCENT ETHNICITY UNKNOWN      0.000         NaN
26                COUNT ETHNICITY TOTAL      9.400         NaN
27              PERCENT ETHNICITY TOTAL     79.900         NaN
28       COUNT PERMANENT RESIDENT ALIEN      0.500         NaN
29     PERCENT PERMANENT RESIDENT ALIEN      0.061         NaN
30                     COUNT US CITIZEN      8.900         NaN
31                   PERCENT US CITIZEN      0.739         NaN
32           COUNT OTHER CITIZEN STATUS      0.000         NaN
33         PERCENT OTHER CITIZEN STATUS      0.000         NaN
34         COUNT CITIZEN STATUS UNKNOWN      0.000         NaN
35       PERCENT CITIZEN STATUS UNKNOWN      0.000         NaN
36           COUNT CITIZEN STATUS TOTAL      9.400         NaN
37         PERCENT CITIZEN STATUS TOTAL     80.000         NaN
38     COUNT RECEIVES PUBLIC ASSISTANCE      2.300         NaN
39   PERCENT RECEIVES PUBLIC ASSISTANCE      0.151         NaN
40    COUNT NRECEIVES PUBLIC ASSISTANCE      7.100         NaN
41  PERCENT NRECEIVES PUBLIC ASSISTANCE      0.649         NaN
42      COUNT PUBLIC ASSISTANCE UNKNOWN      0.000         NaN
43    PERCENT PUBLIC ASSISTANCE UNKNOWN      0.000         NaN
44        COUNT PUBLIC ASSISTANCE TOTAL      9.400         NaN

## Level Up (Optional)

### Loading Corrupt CSV files

Occassionally, you encountered some really ill formatted data. One example of this can be data that has strings containing commas in a csv file. Under the standard protocol, when this occurs, one is suppossed to use quotes to differentiate between the commas denoting fields and commas within those fields themselves. For example, we could have a table like this:  

ReviewerID,Rating,N_reviews,Review,VenueID
123456,4,137,This restuarant was pretty good, we had a great time.,98765

Which should be saved like this if it were a csv (to avoid confusion with the commas in the Review text):
"ReviewerID","Rating","N_reviews","Review","VenueID"
"123456","4","137","This restuarant was pretty good, we had a great time.","98765"

Attempt to import the corrupt file, or at least a small preview of it. It is appropriately titled Yelp_Reviews_corrupt.csv. Investigate some of the intricacies of skipping rows to then pass over this error and comment on what you think is going on.

In [ ]:
#Hint: here's a useful programming pattern to use.
try:
    #do something
except Exception as e:
    #handle your exception e

In [ ]:
#Your code here